import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/providers";

import { gentium, gentiumBold, telex } from "@/utils/fonts";

import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viweport: "width=device-width, initial-scale=1.0"
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${gentium.variable} ${gentiumBold.variable} ${telex.variable}`}>
      <body className={inter.className}>
        <Providers>
          <Header/>

        <main>{children}</main>

        </Providers>
      </body>
    </html>
  );
}
